apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactapp
  name: reactapp
  namespace: _{_NAMESPACE_}_
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3080
  selector:
    app: reactapp 
  type: LoadBalancer
