//workflow for application
name: Reactapp Workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  
jobs:
  unit-testing:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Nodejs version-10
        uses: actions/setup-node@v3
        with:
          node-version: 10
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
        working-directory: ./api
      - name: Unit testing
        run: npm test
        working-directory: ./api
      - name: Archive test result
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: ./api/test-result.json
  docker:
    name: Containerization
    permissions: 
      packages: write
    runs-on: ubuntu-latest
    needs: [unit-testing]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Docker image testing
        run: |
          docker images
          docker run --name reactapp -d \
            -p 3080:3080 \
            reactapp /reactapp:${{ github.sha }}
          export IP=$( docker inspect -f '{{ range.NetworkSettings.Networks }}{{ .IPAddress }}{{ end }}' reactapp)
  dev-deploy:
    needs: docker
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      -  name: deploy to azure
        uses: azure/azure-deploy@v1
        with:
        package: ./api
        resource-group: testvmwebapp_group
        server-name: stagingservertest
        slot: staging




